# commonLabels these labels are added to all the manifests
commonLabels:
  owner_team: ops-devops
  tech: postgres
  type: pgdb

commonAnnotations:
  categories: database

image:
  name: CHANGEME/postgres-cnpg:16.3-b0
  pullSecret: regcred

# nameSuffix to generate db name
nameSuffix: db

# domain part for external service
serviceDomain: svc.cluster.local

serviceAccount:
  create: true
  name: postgres-pod

minio:
  bucket: s3://pgbackup
  endpoint: http://minio-cluster.tooling:9000
  secret: minio-s3

vault:
  path: /vault/secrets/minio

backup:
  enabled: true
  snapshot: false
  schedule: "0 0 0 * * 1"
  retention: 8d

# delay in seconds before failover (1 week)
failoverDelay: 604800

# rolling update process is managed by operator
primaryUpdateStrategy: unsupervised

priorityClassName: topolvm

# base postgresql config
postgresConfig: postgres-base-conf

postgresql:
  shared_preload_libraries:
    - auto_explain
    - decoderbufs
    - passwordcheck
    - pg_cron
    - pg_failover_slots
    - pg_repack
    - pg_stat_statements
    - pgaudit
  # default parameters
  parameters:
    include_dir: "/projected/config"
  custom_parameters: {}

pooler:
  enabled: true
  image: CHANGEME/pgbouncer-cnpg:1.22.1-b1
  mode: transaction
  instances: 2
  paused: false
  parameters:
    max_client_conn: "1000"
    default_pool_size: "10"

exporter:
  # prometheus discovery label
  release: prometheus-dbs
  configMapName: postgres13-exporter-cm

# cluster instances
databases: []

# database defaults that can be overwritten per-instance
default:
  # prepared databases
  databases: {}
  # prepared roles
  roles: {}
  # storage PVC size for each instance
  storage: 10Gi
  # pod resource requests
  requests:
    cpu: 500m
    memory: 1Gi
  # pod resource limits
  limits: {}
  # number of postgres instances
  instances: 2
  # nodeAffinity
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: pgdb
          operator: In
          values:
          - "true"
