# commonLabels these labels are added to all the manifests
commonLabels: {}

commonAnnotations:
  categories: database

podEnv:
- name: KUBE_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: ENV_NAME
  valueFrom:
    configMapKeyRef:
      name: environment-name
      key: env
      optional: true

image:
  registry: ghcr.io
  repository: cloudnative-pg/postgresql
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullSecret: ""

# nameSuffix to generate db name
nameSuffix: db

# domain part for external service
serviceDomain: svc.cluster.local

serviceAccount:
  create: true
  name: postgres-pod

s3:
  bucket: s3://pgbackup
  endpoint: http://seaweedfs-s3.seaweedfs:8333
  secret: seaweedfs-s3

backup:
  enabled: false
  snapshot: false
  schedule: "0 0 0 * * *"
  retention: 8d

# delay in seconds before failover (1 week)
#failoverDelay: 604800

# rolling update process is managed by operator
primaryUpdateStrategy: unsupervised

priorityClassName: ""

# base postgresql config
postgresConfig: postgres-base-conf

postgresql:
  shared_preload_libraries:
    - auto_explain
    - decoderbufs
    - passwordcheck
    - pg_cron
    - pg_failover_slots
    - pg_repack
    - pg_stat_statements
    - pgaudit
  # default parameters
  parameters:
    include_dir: "/projected/config"
  custom_parameters: {}

pooler:
  enabled: true
  image: ghcr.io/cloudnative-pg/pgbouncer:1.23.0
  mode: transaction
  instances: 2
  paused: false
  parameters:
    max_client_conn: "1000"
    default_pool_size: "10"

exporter:
  # prometheus discovery label
  release: prometheus-dbs
  configMapName: postgres-exporter-cm

# additional postgres config
config: ""

# cluster instances
databases: []

affinity:
  enablePodAntiAffinity: true
  topologyKey: hw_host
  nodeAffinity: {}
  #  requiredDuringSchedulingIgnoredDuringExecution:
  #    nodeSelectorTerms:
  #    - matchExpressions:
  #      - key: pgdb
  #        operator: In
  #        values:
  #        - "true"
  #      - key: node-type
  #        operator: NotIn
  #        values:
  #        - "bare-metal"

# database defaults that can be overwritten per-instance
default:
  # prepared databases
  databases: {}
  # prepared roles
  roles: {}
  # storage PVC size for each instance
  storage: 10Gi
  # pod resource requests
  requests:
    cpu: 100m
    # mebibyte
    memory: 200Mi
  # pod resource limits
  limits: {}
  # number of postgres instances
  instances: 2
  # nodeSelector
  nodeSelector: {}
