# for testing only
databases:
- name: warehouse
  instances: 2
  storage: 2Gi
  pooler:
    enabled: true
  service:
    name: warehouse
    external: true
    namespaces:
      - apps
  config: postgres-conf-dev
  adminSecret: warehouse-db
backup:
  schedule: "0 0 * * * *"
  retention: 1d
