{{- range $d := .Values.databases }}
{{- $instanceName := printf "%s-%s" $d.name $.Values.nameSuffix }}
{{- $instancePooler := hasKey ($d.pooler) "enabled" | ternary ($d.pooler).enabled $.Values.pooler.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $instanceName }}-exporter
  labels:
    {{- include "core.labels" $ | nindent 4 }}
    {{- toYaml $.Values.exporter.labels | nindent 4 }}
    name: {{ $instanceName }}-exporter
spec:
  podMetricsEndpoints:
  - port: metrics
    relabelings:
    - action: replace
      sourceLabels: [ __meta_kubernetes_pod_label_app_kubernetes_io_instance ]
      targetLabel: app_instance
    metricRelabelings:
    - action: replace
      sourceLabels: [ __name__ ]
      targetLabel: '__name__'
      regex: 'cnpg_(dba_.*)'
      replacement: '$1'
    - action: replace
      sourceLabels: [ pod ]
      targetLabel: instance
      regex: '(.+)-\d'
    - action: drop
      sourceLabels: [ __name__ ]
      regex: '^go_.+$'
  selector:
    matchLabels:
      cnpg.io/cluster: {{ $instanceName }}
      cnpg.io/podRole: instance
      type: pgdb
{{- /* pooler PodMonitor */}}
{{- if eq (toString $instancePooler) "true" }}
{{- range list "rw" "ro" }}
{{ $poolerName := printf "%s-%s-%s" $instanceName "pooler" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/poolerName: {{ $poolerName }}
    release: {{ $.Values.exporter.release }}
  name: {{ $poolerName }}
spec:
  podMetricsEndpoints:
  - bearerTokenSecret:
      key: ""
      name: ""
    port: metrics
  selector:
    matchLabels:
      cnpg.io/poolerName: {{ $poolerName }}
{{- end }}
{{- end }}
{{- end }}
