{{- if eq (toString .Values.serviceAccount.create) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: {{- include "core.labels" . | nindent 4 }}
{{- end }}
